### ISSUE TITLE
No support for $ref

### ISSUE THREAD

**Issue by shakyShane** [StefanTerdell/json-schema-to-zod#1]
Hi, I appreciate the simplicity of this library. But without support for resolving $ref's, it makes it quite limited for anything other than simple schemas. Have you considered adding support for $ref?

Thanks :)

**Comment by StefanTerdell** [comment]
This is in master now. Will release when I have time to test and play around with it a bit more.

**Comment by StefanTerdell** [comment]
Released in 0.1.1. Use -d in the cli.
