### ISSUE TITLE
`--type` argument ignored

### ISSUE THREAD

**Issue by dreglad** [StefanTerdell/json-schema-to-zod#102]
Currently, the `--type` argument has no effect in the CLI.

Looking at `cli.ts`, I noticed that `type` is listed as a valid parameter but isn’t being passed as an option to the `jsonSchemaToZod()` call.

Is it actually unsupported, or was it just missed?

---

I also submitted this PR #103 to fix a typo for the `--output` argument shorthand in the README file which was confused with `--type`.

**Comment by StefanTerdell** [comment]
Woops! Fixed in 2.3.1.
