### ISSUE TITLE
Make describes optional

### ISSUE THREAD

**Issue by aidinabedi** [StefanTerdell/json-schema-to-zod#104]
Like with defaults, there are cases where it's undesirable to have describes. When descriptions are long, including them may result in less readable zod schemas. Additionally, you may not want describes to be included in production builds.

I humbly propose a new simple option `withoutDescribes`, analogous to `withoutDefaults`. See my PR #105.

**Comment by StefanTerdell** [comment]
@aidinabedi Nice! Merged and released as `2.4.0`. Oh, and thanks for actually reading contributing.md :D
