### ISSUE TITLE
Generating zod schema at runtime

### ISSUE THREAD

**Issue by tonyxiao** [StefanTerdell/json-schema-to-zod#12]
The output here appears to be a string defining Zod schema, however I don't always know the JSONschema I am getting ahead of time and it would be incredibly useful to be able to get a zod schema at runtime rather than a string that needs to be put into a file at compile time.

**Comment by StefanTerdell** [comment]
@tonyxiao  There are no plans for that at the moment. Your options are to validate your values using a json schema validator like Ajv or using `eval()`.

Discussed in previous issue: https://github.com/StefanTerdell/json-schema-to-zod/issues/2
