### ISSUE TITLE
Question: How to use at runtime? 

### ISSUE THREAD

**Issue by jjherscheid** [StefanTerdell/json-schema-to-zod#2]
Great package, but I was wondering how I can use this library at runtime, because the output will be a string instead of the zod object structure.

We have an endpoint that returns the json schema and I would like to convert the schema runtime to zod.

Thanks in advance

**Comment by StefanTerdell** [comment]
That's not the purpose of this package unfortunately. It only creates a string. I was thinking of doing a rewrite that first traversed the json schema and created an actual Zod schema and then traversed that to turn it into a string, but as I'm no longer using Zod professionally I've not gotten around to it and I'm not super likely to do so in the foreseeable future.

As always, I'm open to PRs.

**Comment by jjherscheid** [comment]
Ok, thanks for the answer. I have decided to use another validation library 'ajv' for our situation.

**Comment by StefanTerdell** [comment]
Yeah that seems like the best approach either way, always best to keep things as untranslated as possible. Reopening this though since I still would like to make the feature at some point.

**Comment by cyrus-za** [comment]
I'd love to get this feature going. If you can point me in the right direction I can open up a PR

**Comment by StefanTerdell** [comment]
I removed the "help wanted" label because it's basically too big of an ask I guess :D 
I may get around to this during my vacation later this summer, we'll see.

**Comment by StefanTerdell** [comment]
I guess in the meantime one workaround is you could just eval the result. As in:

```
import { z } from "zod"

const myZodSchema = eval(jsonSchemaToZod(myJsonSchema))
```

With the recent code security updates it _should theoretically_ be pretty safe. Disclaimer: Not a financial advisor, lawyer or good at make computer do thing.

The only _correct_ answer as I see it it to just use Ajv. Zod is first and foremost a write time tool IMHO.

**Comment by jjherscheid** [comment]
`eval()` is an evil option ;-)..

**Comment by p6l-richard** [comment]
Hi @StefanTerdell,

Unfortunately, mine is just a suggestion -- I don't have the bandwidth currently to open a PR (sorry about this).

However, when trying out the package today, I noticed that I'm getting a TS error when providing the JSON schema that ajv accepts & compiles correctly. 
[Reproduction here](https://codesandbox.io/s/tripetto-json-schema-z6kph6?file=/src/index.ts:311-503).

So I'm wondering if accepting ajv's input types for the schema could be part of the work you suggested above.
- [JSONSchemaType](https://github.com/ajv-validator/ajv/blob/master/lib/types/json-schema.ts#L143-L146)
- [SchemaObject](https://github.com/ajv-validator/ajv/blob/master/lib/types/index.ts#L15-L21)

**Comment by StefanTerdell** [comment]
@p6l-richard moved to https://github.com/StefanTerdell/json-schema-to-zod/issues/6

**Comment by StefanTerdell** [comment]
I realized I'm not ever gonna get around to this because I kinda don't care. If you need to validate your JSON schemas at runtime, use a tool for that ([AJV ](https://www.npmjs.com/package/ajv) being the "industry standard").
