### ISSUE TITLE
CLI executable isn't being found

### ISSUE THREAD

**Issue by brandonpittman** [StefanTerdell/json-schema-to-zod#22]
Trying to run the CLI tool, but the command isn't being found.

![CleanShot 2022-11-18 at 10 34 53@2x](https://user-images.githubusercontent.com/967145/202596466-b2d599e4-a915-4ea1-8a1c-60d63fddba85.png)

Looked at the `package.json`, it's pointing to `./cli.js`, but maybe it needs to look at `./src/cli.js`?

Running the CLI directly from `node_modules` works.

![CleanShot 2022-11-18 at 10 36 30@2x](https://user-images.githubusercontent.com/967145/202596635-cc024607-21dd-4d2d-bbc8-4e7ba671e5e7.png)

**Comment by StefanTerdell** [comment]
Doh, I forgot to exclude the test folder from the build. Fixed in 0.3.1, just released
