### ISSUE TITLE
Problem parsing FHIR schema

### ISSUE THREAD

**Issue by timneedham** [StefanTerdell/json-schema-to-zod#25]
Hi,

**Great project!**

I'm trying to parse the [FHIR JSON schema](http://hl7.org/fhir/validation.html) (attached [fhir.schema.zip](https://github.com/StefanTerdell/json-schema-to-zod/files/10145992/fhir.schema.zip)) 

But the output is much smaller than anticpiated.
I'm very new to Zod and FHIR so I'm sure this is user error... but the results of `jsonSchemaToZod` is "just":

```
    import { z } from "zod";
    
    export default z
      .any()
      .superRefine((x, ctx) => {
        const schemas = [
          z.any(),
          z.any(),
          // ...
        ];
        const errors = schemas.reduce(
          (errors: z.ZodError[], schema) =>
            ((result) => ("error" in result ? [...errors, result.error] : errors))(
              schema.safeParse(x)
            ),
          []
        );
        if (schemas.length - errors.length !== 1) {
          ctx.addIssue({
            path: ctx.path,
            code: "invalid_union",
            unionErrors: errors,
            message: "Invalid input: Should pass single schema",
          });
        }
      })
      .describe(
        "see http://hl7.org/fhir/json.html#schema for information about the FHIR Json Schemas"
      );
```

* I had expected this to be a monster? :smile: 

Any help gratefully received. 
Thanks again for a great project.

**Comment by timneedham** [comment]
I get slightly more in your playground, BTW... but still not all the fields I was expecting?

**Comment by StefanTerdell** [comment]
1. Zod doesn't have the equivalent of oneOf which this schema uses _alot_. Hence the superRefine. It's an approximation, but doesn't produce a usable TS type.
2. The reason you get more in the demo is that your input is dereferenced there, meaning the "links" in all the $ref statements get resolved. Try using the cli with the `-d` flag, or use the `jsonSchemaToZodDereffed` function if you're using it programmatically.

**Comment by timneedham** [comment]
Ah I see... great, thanks for the explanation!
