### ISSUE TITLE
This outputs returns a string, how can I use this with Zod to parse?

### ISSUE THREAD

**Issue by notflip** [StefanTerdell/json-schema-to-zod#27]
I'm trying to do the following

```
const parsed = parseSchema(schema)
parsed.parse(lonenModel)
```

But this just returns a string
```
z.object({"id":z.number().int(),"klant_id":z.union([z.string(),z.null()]).optional(),"lgrp_id":z.union([z.string(),z.null()]).optional(),"wgnr_id":z.union([z.string(),z.null()]).optional(),"klant_naam":z.union([z.string(),z.null()]).optional(),"datum_afdruk":z.union([z.string(),z.null()]).optional(),"tijd_afdruk":z.union([z.string(),z.null()]).optional(),"extensie":z.union([z.string(),z.null()]).optional(),"kopies":z.union([z.string(),z.null()]).optional(),"extra-info":z.union([z.string(),z.null()]).optional(),"opdrachtnr":z.union([z.string(),z.null()]).optional(),"EfichesPdfPcl":z.union([z.string(),z.null()]).optional()})
```

**Comment by StefanTerdell** [comment]
You could use `eval`, but the question is why you would want to do this in the first place..? Zod has no real advantages over JSON schema in a runtime environment when using a validator such as AJV. In fact, some specifics are always at risk of getting lost in translation, and AJV is a lot faster as well.

The idea with this package is to aide in migrating from a collection of existing JSON schemas to Zod schemas in form of typescript files.

**Comment by notflip** [comment]
I'm using Sequelize as an ORM, I found a plugin that can transform Sequelize models to JSON schema, in combination with this plugin I would then be able to use zod to validate data according to the Sequelize models I have. Do you think there's an easier way to accomplish this?

**Comment by StefanTerdell** [comment]
I'm going to close this issue as it doesn't pertain to this package directly. Good luck :)

**Comment by rmlevangelio** [comment]
I'm curious about this as well. We wanted to use the JSON schema as main source of truth and we want to use the properties defined in JSON schema in the frontend.

**Comment by zacherkkila** [comment]
For those wondering how to do this (note: `eval` and `new Function` have their own inherent security risks, this is worth evaluating for your usage)

Also, as @StefanTerdell mentioned, there may be another way for you to obtain your goal directly..

In my unique case, I build a large `zod` object, and some properties of that object are json schemas. I use this to generate a typescript interface (as a string) at runtime that describes the type of a dataset (the type and data are used in further scripting in another process). We `infer` the type of the `zod` object so it throws compile time errors if we pass the wrong values to the dataset and can use `zod` for runtime checks as well. This gives us both a compile time check and the ability to make sure the interface we pass forward matches that dataset.

I could also use this https://www.npmjs.com/package/json-schema-to-typescript and pull out the schema types and re-merge them to the typescript interface but this seemed a little nicer and allows for a runtime check on the schema.

```
import { z } from 'zod'
import { parseSchema } from 'json-schema-to-zod'

const zodSchema = parseSchema(myJsonSchema)

const args = '...args'
const convert = new Function(args, `const [z] = args; const schema = ${zodSchema}; return schema;`)

// obviously typings via `infer` are not available here as the json schema is coming in at runtime
// but the typescript conversion using zodToTs works just fine
const zod = convert(z) 
```

**Comment by Aeolun** [comment]
I'd like this _because_ we're migrating from json schema to Zod. All the legacy schemas are json schema, but if we were to convert all schemas to zod in one go, we'd also need to modify legacy code to suddenly use zod. While we're integrating with the new code it would be very nice to be able to use the old json schemas (e.g. old code can remain the same) but do the validation with zod.

**Comment by KenjiEmura** [comment]
How can I convert that string to an actual zod object? I need to pass a zod object to my react-hook-fom [resolver](https://github.com/react-hook-form/resolvers#zod) (I'm trying to build a dynamic form generator) but I can't do that if the parseSchema returns a string. Please help me.

**Comment by claritise** [comment]
Similarly looking to do this as I am using zod for building input/output schemas in langchain. These schemas are built and stored during runtime and need to be serialised and deserialised..
