### ISSUE TITLE
package.json schema doesn't work

### ISSUE THREAD

**Issue by gtflip** [StefanTerdell/json-schema-to-zod#34]
I'm trying to create a schema based on the [package.json schema](https://json.schemastore.org/package.json), and it has some problems.

The online demo gives `InternalError: too much recursion`.

Running the cli on it with no "--deref" isn't useful, since it gives things like `dependencies: z.any()` when it should be a `z.object()` or `z.record()`.

Running the cli on it with "--deref" gives `RangeError: Maximum call stack size exceeded`

**Comment by StefanTerdell** [comment]
Really tired of these deref issues.. Related to #29 and #36.

**Comment by StefanTerdell** [comment]
Fixed in 1.0.0

Output is like 120k lines though but yeah.
