### ISSUE TITLE
Would you consider a change to make the code generation interface generic?

### ISSUE THREAD

**Issue by mrdziuban** [StefanTerdell/json-schema-to-zod#37]
Hello! Thank you for your hard work on this, it's a really great tool.

I'm interested in doing something very similar for generating `io-ts` codecs and have been fiddling with modifying the `parse*.ts` files to support generic code generation implementations, e.g. a user could choose between `zod`, `io-ts`, or any other option as long as they can conform to the required implementation interface.

Would you consider a pull request with this change or does it go too far outside the relevant scope?

**Comment by StefanTerdell** [comment]
@mrdziuban Thanks for the interesting topic! But, ask any [grug brained developer](https://grugbrain.dev/) and they will tell you complexity very, very bad. To avoid this I'd go for a fork if I were in your shoes. Feel free to build upon it any way you want to, but generalizing the code generation wouldn't leave much in place, and none of it would improve on the core functionality of the current code base.
