### ISSUE TITLE
Broken install of CLI on Mac when using Yarn

### ISSUE THREAD

**Issue by Don-Ghead** [StefanTerdell/json-schema-to-zod#38]
Prefacing this by making it clear that i'm aware on your docs you provide the command with NPM and not Yarn but I feel like many people will have a preference and will try to do it with Yarn regardless.

When installing the package via `yarn global add json-schema-to-zod` and attempting to run any associated command with it I get an error `env: node\r: No such file or directory`. This is due to the fact that NPM auto converts line endings but Yarn does not and requires a bit of help. 

The fix for this was to use npx to convert after install like so `npx crlf --set=LF /path/to/json-schema-to-zod`

**Comment by StefanTerdell** [comment]
Should be fixed in 0.6.3
