### ISSUE TITLE
Unclear behavior on what happens if an invalid schema is provided

### ISSUE THREAD

**Issue by andenacitelli** [StefanTerdell/json-schema-to-zod#41]
Could use improved documentation on this scenario. Is an error thrown? Is a `z.any()` schema output, as implied by [this issue](https://github.com/StefanTerdell/json-schema-to-zod/issues/36) and a quick test I just ran? 

My use case is that I'm trying to allow consumers of my API to specify a JSON schema as part of their payload, which I then parse with this library and use it to parse something before I return it to them.

**Comment by StefanTerdell** [comment]
`z.any()` will be the likely fallback. But as I mentioned in another one of your registered issue, in your case I'd simply not convert it to Zod at all. Just use Ajv.
