### ISSUE TITLE
How to take output Schema string and parse something with it?

### ISSUE THREAD

**Issue by andenacitelli** [StefanTerdell/json-schema-to-zod#46]
I have this library successfully converting the json schema to a stringified representation of a Zod schema, but am at a loss on how to actually parse something with it. I'm trying to dynamically take a JSON Schema via payload argument, convert it to Zod, and use it to validate all in one web request.

My first thought would be something like `eval`, but that doesn't seem great from a security standpoint.

**Comment by StefanTerdell** [comment]
@andenacitelli That's currently your only option. It should be pretty safe to eval.

However, I'm left wondering why you need to convert the JSON schema in the first place. Why not just use Ajv?
