### ISSUE TITLE
allOf is not converted properly

### ISSUE THREAD

**Issue by MightyMorpheus** [StefanTerdell/json-schema-to-zod#49]
There is some issue with 'allOf'

Schema:
`"someProperty": {
	"description": "ABCD",
	"type": "object",
	"allOf": [
		{
			"type": "object",
			"properties": {
				"entryId": {
					"description": "id",
					"type": "string",
					"example": "VYP3"
				},
				...
			},
			"required": ["entryId"]
		},
		{
			"type": "object",
			"properties": {
				"otherValues": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {...},
						"required": ["value", "key"]
					}
				},
				...
			}
		}
	],
},`

Result:
`someProperty: z.record(z.any()).describe("ABCD").optional(),`

I probably find where the problem is. It is in 'selectParser' function, where code goes to isObject way and 'allOf' else if is not hit at all.

**Comment by StefanTerdell** [comment]
Yeah, combining keywords like that just isn't supported currently.

Open to PRs :)

**Comment by StefanTerdell** [comment]
Not exactly "fixed" in 1.0.0, but close enough for most use cases IMHO.2
