### ISSUE TITLE
Schema including `patternProperties` resulting in `z.any()`

### ISSUE THREAD

**Issue by bachorp** [StefanTerdell/json-schema-to-zod#51]
When processing the compose spec schema (available from https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json) all top-level object values will be of type `z.any()`. The validator will output rich types if we remove `patternProperties` from the schema.
If I'm not mistaken, we should, however, be able to handle `patternProperties` by using a `z.record(keyType, valueType)` (https://github.com/colinhacks/zod#record-key-type).

**Comment by magick93** [comment]
I'm also running into this issue.
Has anyone found a solution?

**Comment by StefanTerdell** [comment]
Fixed in 1.0.0. With `patternProperties` the schema keys represent regular expressions to match the value keys against. Zod doesn't support anything like this at all, so it's using a `superRefine` under the hood. The schemas get pretty huge. Works though.
