### ISSUE TITLE
Always giving z.any() in output

### ISSUE THREAD

**Issue by Royal-lobster** [StefanTerdell/json-schema-to-zod#55]
Passing the converted JSON Schema from the sister package to this gives out z.any() always. attaching a screenshot which tries to convert the example from https://www.npmjs.com/package/zod-to-json-schema directly on demo app, it produces the same result.

<img width="910" alt="CleanShot 2023-06-26 at 06 42 09@2x" src="https://github.com/StefanTerdell/json-schema-to-zod/assets/52039218/a48a8eed-7dac-4695-a44b-88d3649d6552">

**Comment by StefanTerdell** [comment]
Fixed in 1.0.0
