### ISSUE TITLE
parseSchema requires second "Refs" argument?

### ISSUE THREAD

**Issue by stubailo** [StefanTerdell/json-schema-to-zod#61]
Hi, I'm trying to update to 1.0+, and my code has something like this:

```
import { parseSchema } from 'json-schema-to-zod';

// ...

// Convert to Zod
const zodSchema = parseSchema(jsonSchema);
```

As of 1.0.0, I'm seeing a type error that parseSchema requires a second argument.

In the README in the repo here, the sample code seems to just call parseSchema with only one argument. Do you have a code sample for how to pass the refs argument? Or, is it possible to make it so that parseSchema can be called with no arguments?

Let me know if I can help!

**Comment by StefanTerdell** [comment]
Fixed in 1.1.1
