### ISSUE TITLE
No support Native enums

### ISSUE THREAD

**Issue by yokoyama-takuya** [StefanTerdell/json-schema-to-zod#7]
Thank you for the awesome library!
I want an [Native enums](https://github.com/colinhacks/zod#native-enums) option.

e.g.

input schema
```json
{
	"type": "object",
	"properties": {
		"testType": {
			"type": "number",
			"enum": [
				1,
				2
			]
		}
	}
}
```

output
```ts
import { z } from "zod";

export default z.object({ testType: z.enum([1, 2]).optional() });
```

Zod enums only support string types, so you will get an error.

expected results

```ts
import { z } from "zod";

const testType = {
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;

export default z.object({ testType: z.nativeEnum(testType).optional() });
```

**Comment by StefanTerdell** [comment]
Hello @yokoyama-takuya! Thanks for bringing this issue to attention. [I believe I have resolved it with this commit.](https://github.com/StefanTerdell/json-schema-to-zod/commit/69d2a8f1fe2d1d141d0d2955cc5dab53e7fb5452). It's available now as part of the latest patch release.

Before this commit, the package produced faulty code as you pointed out:

```json
{ "enum": ["x", 0, null, true] }
```
...would produce:
```typescript
z.enum(["x", 0, null, true])
```

...which would indeed create an error. Now it produces this (if not all values are strings):
```typescript
z.union([z.literal("x"), z.literal(0), z.literal(null), z.literal(true)])
```

I believe this to be the most accurate translation of the json schema `enum` keyword as the values in the array lack property names. I could see a case for using native enums on object schemas where all properties are of type string or number and have associated `const` keywords, but this would probably have to be optional and treated differently.

Let me know if you think this closes the issue.

**Comment by yokoyama-takuya** [comment]
@StefanTerdell  Thanks for the fix!
I never had the idea to use `union`. It's a smart fix and nice.
