### ISSUE TITLE
add missing IP addresses string validations

### ISSUE THREAD

**Issue by geko1971** [StefanTerdell/json-schema-to-zod#71]
Hello Stefan, first of all congrats for your really helpful lib!

It would be great to add the missing string format validations that are part of [JSON format assertion vocabulary](https://json-schema.org/draft/2020-12/json-schema-validation#name-format-assertion-vocabulary), maybe starting from the ones that maps easily with zod assertions, such as [IP Addresses validations](https://json-schema.org/draft/2020-12/json-schema-validation#name-ip-addresses).

That could only require a small change to `src/parsers/parseString.ts` module:

```diff
import { JSONSchema7 } from "json-schema";

export const parseString = (schema: JSONSchema7 & { type: "string" }) => {
  let r = "z.string()";
  if (schema.pattern)
    r += `.regex(new RegExp(${JSON.stringify(schema.pattern)}))`;
  if (schema.format === "email") r += ".email()";
+  if (schema.format === "ip") r += ".ip()";
+  if (schema.format === "ipv4") r += ".ip({ version: "v4" })";
+  if (schema.format === "ipv6") r += ".ip({ version: "v6" })";
  else if (schema.format === "uri") r += ".url()";
  else if (schema.format === "uuid") r += ".uuid()";
  else if (schema.format === "date-time") r += ".datetime()";
  if (typeof schema.minLength === "number") r += `.min(${schema.minLength})`;
  if (typeof schema.maxLength === "number") r += `.max(${schema.maxLength})`;
  return r;
};
```

Thank you!

**Comment by grmkris** [comment]
hello i'd like to achieve the same for date fields

```
"birthday": {
                  "title": "Birthday",
                  "type": "string",
                  "format": "date"
                },
```

**Comment by StefanTerdell** [comment]
@grmkris Date and time formats have no equivalents in Zod, sorry

**Comment by grmkris** [comment]
we could do z.coerce.date() ?

**Comment by eriktim** [comment]
> @grmkris Date and time formats have no equivalents in Zod, sorry

They actually got added recently: https://github.com/colinhacks/zod/pull/1766
