### ISSUE TITLE
"not" patterns

### ISSUE THREAD

**Issue by MrVauxs** [StefanTerdell/json-schema-to-zod#76]
Hello, love the module, makes my work much easier except for one issue.

It seems that the module does not allow for usage of "not" patterns? For example, the following schema returns a normal looking zod script
```json
{
  "type": "object",
  "properties": {
    "hello": {
      "type": "string",
      "minLength": 1
    }
  }
}
```
```js
export default z.object({ hello: z.string().min(1).optional() });
```

However, by adding a `not` pattern into it, it changes to 
```json
{
  "type": "object",
  "properties": {
    "hello": {
      "type": "string",
      "minLength": 1,
      "not": {
        "pattern": "@"
      }
    }
  }
}
```
```js
export default z.object({
  hello: z
    .any()
    .refine(
      (value) => !z.any().safeParse(value).success,
      "Invalid input: Should NOT be valid against schema"
    )
    .optional(),
});
```

Is this a limitation of the module itself, or are we doing something not recommended?

**Comment by MrVauxs** [comment]
I am guessing it should be something I just write a parser for.

**Comment by StefanTerdell** [comment]
It's just a case that isn't covered (yet). The amount of combinations you can do with json schema is nearly endless and it all has to be funneled down to mostly sane Zod equivalents. If you added a type to the not schema it gets clearer, but it still treats the not node as its own complete schema unfortunately.

I'm not personally interested in pursuing a solution to that honestly as 95% is good enough for me, but I'd welcome PRs addressing the issue systematically

**Comment by StefanTerdell** [comment]
Folding into #79
