### ISSUE TITLE
Incorrect order for nullable/default

### ISSUE THREAD

**Issue by robogeek** [StefanTerdell/json-schema-to-zod#77]
I'm seeing an error in code generated by `openapi-to-zod`.  That package uses this package to generate code.

For an OpenAPI schema with `nullable: true` and `default: true` the generated code is:

```
$ cat zod/zod-hasDefaultNull.ts 
import { z } from "zod";

export default z.object({
  defaultNull: z.string().datetime().default(null).nullable().default(null),
});
```

The first `default(null)` causes the compiler to complain that it's not allowed.

https://github.com/Apollo314/openapi-to-zod/issues/5

**Comment by StefanTerdell** [comment]
Fixed! Released as 2.0.13
