### ISSUE TITLE
"oneOf" as union?

### ISSUE THREAD

**Issue by davedoesdev** [StefanTerdell/json-schema-to-zod#78]
Could `oneOf` be represented as [`union`](https://zod.dev/?id=unions) instead of a refined `any`? It would make the output read better and better suited to further processing.

**Comment by StefanTerdell** [comment]
No, `oneOf` is exclusive, `union` is inclusive. Use `anyOf` in the JSON schema instead, using `oneOf` is almost universally a bad idea.

**Comment by davedoesdev** [comment]
Thanks, that works for my use case :+1:
