### ISSUE TITLE
Web example is broken

### ISSUE THREAD

**Issue by gabrielmar** [StefanTerdell/json-schema-to-zod#82]
https://stefanterdell.github.io/json-schema-to-zod-react/

```json
{
  "foo": "bar"
}
```
![image](https://github.com/StefanTerdell/json-schema-to-zod/assets/38334104/87f20733-2f1b-4736-b82b-0e870c6d3d77)

**Comment by StefanTerdell** [comment]
jfc `{ "foo":"bar" }` is not a json schema

**Comment by gabrielmar** [comment]
> jfc `{ "foo":"bar" }` is not a json schema

wtf???????????
What would a json schema be for you?

**Comment by gabrielmar** [comment]
Delete this issue
