### ISSUE TITLE
Support for more Annotated Keywords

### ISSUE THREAD

**Issue by ethanleifer** [StefanTerdell/json-schema-to-zod#84]
Hi!

Thank you for a great library. 

I am looking to leverage the [examples keyword](https://json-schema.org/understanding-json-schema/reference/annotations). Would this be possible with Zod?

**Comment by StefanTerdell** [comment]
Unfortunately not. There was a proposal to add this to Zod but it never went anywhere. [Here's a link to the issue.](https://github.com/colinhacks/zod/issues/2548)

**Comment by alexrecuenco** [comment]
Forgive the intrusion, but given how there is `zod-openapi` that includes a `.openapi` field, ¿is there any way for a user t hook into json-schema-to-zod to do custom logic? 

I was looking at the internals, and I can't see documentation in how I would go about adding a `[".openapi(", ")"]` custom format, I don't see any plugin process I can hook into, I might be mistaken.

Another example would be how now format:binary is converted to base64() and I'd like that to be ignored as well...
