### ISSUE TITLE
$ref not working with local $defs

### ISSUE THREAD

**Issue by danielFHcode** [StefanTerdell/json-schema-to-zod#96]
## Replication Steps

Compile the following simple schema:

```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$ref": "#/$defs/X",
    "$defs": {
        "X": { "type": "number" }
    }
}
```

(here's a stack blitz link for convenience: https://stackblitz.com/edit/stackblitz-starters-ng9dmz?file=compile.sh)

## Expected result

```ts
import { z } from 'zod';

export default z.number();
```

or alternatively:

```ts
import { z } from 'zod';

export const $defs = {
    X: z.number()
};
export default $defs.X;
```

## Actual result

```ts
import { z } from 'zod';

export default z.any();
```

## Additional Notes

When testing this with http references, it also didn't work, but I asum making http requests is out of scope for this library.

**Comment by StefanTerdell** [comment]
@danielFHcode Since v2 resolving references is out of scope entirely and you will need to resolve them "manually" beforehand. If you're using the CLI, you can pipe the output from a resolver CLI. If your schemas contain circular data you will need to do it programmatically.

**Comment by brunolemos** [comment]
@danielFHcode do you have any script for this?
