### ISSUE TITLE
Reusable schemas from refs

### ISSUE THREAD

**Issue by petr166** [StefanTerdell/json-schema-to-zod#97]
Hi there 👋!

Thanks for your work on the lib! 
I'm interested to know if there's an option or a plan to add one for creating zod schemas from refs rather than resolving and repeating the definition code. 

My use case has a somewhat complex json type def that is referenced many times. This results in going from ~1k lines json schema file to 20k zod, not ideal.

**Comment by StefanTerdell** [comment]
Good lord no, that sounds like a nightmare! :D

Probably doable, but the blast radius would be big enough for it to warrant a completely new project.
