### ISSUE TITLE
Make import { z } from "zod"; optional

### ISSUE THREAD

**Issue by GerbenRampaart** [StefanTerdell/json-schema-to-zod#98]
Can we make this import optional? I think putting it behind a config flag (with true as default) makes it nicely backward compatible and it would an easy config. 

This project is ideal in my situation (I'm building a code generator) but I don't want the import because I get this:

![2024-06-28 11 41 30](https://github.com/StefanTerdell/json-schema-to-zod/assets/1949178/5f5dd4ab-f97c-47fc-ab34-d84e4909da7f)

Now to be clear, it's obviously easy to just output.replace it away, but that seems like a hack after.

**Comment by StefanTerdell** [comment]
Try the module = none option :)

**Comment by GerbenRampaart** [comment]
Forget I said anything ! :-)
