### ISSUE TITLE
Add optional infer

### ISSUE THREAD

**Issue by GerbenRampaart** [StefanTerdell/json-schema-to-zod#99]
One of the great things of zod is that it does both validation and typing. This zod generator could optionally add an infer line like this:

![2024-06-28 11 52 56](https://github.com/StefanTerdell/json-schema-to-zod/assets/1949178/3854f940-f657-4ad7-922f-068d7d7cb13f)

Now, you have both the type and the zod schema

**Comment by StefanTerdell** [comment]
That's not a bad idea actually

**Comment by StefanTerdell** [comment]
@GerbenRampaart Available in 2.2.0
